### ISSUE TITLE
（１）CRUD処理作成　⇒追加処理の作成に変更

### ISSUE THREAD

**Issue by takasaki376** [mo-ri-regen/qin-todo-backend#8]
# ゴール
- TODOの追加処理を作成する。

# やること
- 'cors'の設定を行う（対応難しければ、別にISSUEを立てます。）
- `http://localhost:8000/todo`のPOSTメソッドに対応して、データが１件登録される。
- 登録時にUUIDの自動生成を行う。
- レスポンスは、テーブルの全項目を返す。（採番後のUUIDを返したい。最終的にはユーザIDも返したい。）

#19 のレイアウトでお願いします。

# 参考
- [cors](https://fastapi.tiangolo.com/ja/tutorial/cors/)
- [UUIDの自動生成](https://blog.beaglesoft.net/entry/2019/01/26/102031)

**Comment by mo-ri-regen** [comment]
@takasaki376 
corsの設定で許可するオリジンは決まっているのでしょうか

**Comment by takasaki376** [comment]
> corsの設定で許可するオリジンは決まっているのでしょうか

Herokuにデプロイした場合は、VercelのURLです。
ローカルで動かす場合は、`http://localhost:3000`です。

最終的には、Qinのプロダクトで使うURLになります。（これは、プロダクトとして採用された時の話です。）

**Comment by mo-ri-regen** [comment]
ソースコードを切り替えずに動かせるようにenvファイルに定数として定義したほうがよさそうですね

**Comment by takasaki376** [comment]
ローカルはenvファイルが良いと思います。
